#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'jaeger/thrift/jaeger_types'
require 'jaeger/thrift/zipkin/zipkincore_types'


module Jaeger
  module Thrift
  end
end
