#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'jaeger/thrift/zipkin/zipkincore_types'

module Jaeger
  module Thrift
    module Zipkin
      CLIENT_SEND = %q"cs"

      CLIENT_RECV = %q"cr"

      SERVER_SEND = %q"ss"

      SERVER_RECV = %q"sr"

      WIRE_SEND = %q"ws"

      WIRE_RECV = %q"wr"

      CLIENT_SEND_FRAGMENT = %q"csf"

      CLIENT_RECV_FRAGMENT = %q"crf"

      SERVER_SEND_FRAGMENT = %q"ssf"

      SERVER_RECV_FRAGMENT = %q"srf"

      LOCAL_COMPONENT = %q"lc"

      CLIENT_ADDR = %q"ca"

      SERVER_ADDR = %q"sa"

    end
  end
end
