name: Ruby

on:
  push:
  pull_request:
    branches: [ master ]
  schedule:
    # Runs at 00:00 UTC on the 1st of every month.
    - cron: '0 0 1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.2', '3.0', '3.1']

    services:
      postgres:
        image: docker
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
    - name: Run crossdock
      run: make crossdock
